export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_BY_ID = 'GET_BY_ID';
export const GET_BY_NAME = 'GET_BY_NAME';
export const POST_POKEMONS = 'POST_POKEMONS'
export const GET_TYPES = 'GET_TYPES';
export const FILTER_TYPE = 'FILTER_TYPE';
export const ORDER_ALF = 'ORDER_ALF';
export const ORDER_ATTACK = 'ORDER_ATTACK';
export const FILTER_ORIGIN ='FILTER_ORIGIN';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const CLEAR_DETAIL= 'CLEAR_DETAIL';